### PR TITLE
Second

### PR DESCRIPTION
**Pull request by keshavgoyal2807**
Added profiles page

### CODE REVIEW

**Comment by littlestar642** [comment]
Please read the README.md.

**Comment by keshavgoyal2807** [comment]
DID I MAKE ANY MISTAKE SIR

Sent from Mail for Windows 10

**Comment by littlestar642** [comment]
@keshavgoyal2807 Please follow the convention given in the README for the issue you are taking up. Also try to make different PRs for individual issues

**Comment by littlestar642** [comment]
Closing because of no response

**Pull request closed without merging**
